{"name": "test_al[2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "self = <fff.Test_allure object at 0x0000029F08C01908>, a = 2\n\n    @pytest.mark.parametrize(\"a\",[1,2,3])\n    @allure.severity(allure.severity_level.BLOCKER)\n    \n    @allure.step('我是测试步骤001')\n    def test_al(self, a):\n>       assert a != 2\nE       assert 2 != 2\n\nscripts\\fff.py:12: AssertionError"}, "steps": [{"name": "我是测试步骤001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2\n", "trace": "  File \"d:\\program files\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 157, in impl\n    return func(*a, **kw)\n  File \"D:\\python\\Rep\\scripts\\fff.py\", line 12, in test_al\n    assert a != 2\n"}, "parameters": [{"name": "a", "value": "2"}], "start": 1593873693820, "stop": 1593873693820}], "parameters": [{"name": "a", "value": "2"}], "start": 1593873693820, "stop": 1593873693821, "uuid": "5d9dd99f-fe87-4fa8-bddb-5b34f1a0f0be", "historyId": "2b294d70de3044a60588d9e389013dd3", "testCaseId": "879567248dbe0c1e640f1107f4b35cdd", "fullName": "scripts.fff.Test_allure#test_al", "labels": [{"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "fff"}, {"name": "subSuite", "value": "Test_allure"}, {"name": "host", "value": "bbr1914"}, {"name": "thread", "value": "10872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.fff"}]}